Repository CPE34-KMUTT/pre-freshy-cpe-2021, pull requests merged in 2021-07, with the labels that each got.

#15 Display user and clan assets on dashboard
  .env.example
  public/gallon.png
  public/money.png
  public/star.png
  src/components/contents/dashboard/AssetItem.js
  src/components/contents/dashboard/AssetsList.js
  src/components/contents/dashboard/Balance.js
  src/components/contents/dashboard/Dashboard.js
  src/components/navbar/Navbar.js
  src/components/navbar/ProfileBar.js
  src/middlewares/passport.js
  src/pages/api/clans/[id]/properties.js
  src/pages/index.js
  src/utils/common.js
Labels: enhancement

#18 Implemented admin APIs, complete transfer system and validation
  package.json
  src/components/contents/dashboard/Balance.js
  src/middlewares/permission/admin.js
  src/models/clan.js
  src/models/planet.js
  src/models/stock-history.js
  src/models/transaction.js
  src/pages/api/admin/eternal.js
  src/pages/api/admin/godmod.js
  src/pages/api/admin/market-manipulator.js
  src/pages/api/admin/user-enforcer.js
  src/pages/api/auth.js
  src/pages/api/clans/[id]/stock.js
  src/pages/api/clans/[id]/transfer/fuel.js
  src/pages/api/clans/[id]/transfer/planet.js
  src/pages/api/clans/[id]/transfer/redeem.js
  src/pages/api/clans/[id]/transfer/stock.js
  src/pages/api/users/[id]/transfer/coin.js
  src/utils/axios.js
Labels: enhancement

#19 Implement clan coin donation system and socket io
  jsconfig.json
  package.json
  src/components/common/AlertNotification.js
  src/components/contents/dashboard/AssetsList.js
  src/components/contents/dashboard/Balance.js
  src/components/contents/dashboard/DonateMoneyModal.js
  src/components/forms/LoginForm.js
  src/hooks/useFetch.js
  src/hooks/useSocket.js
  src/middlewares/middleware.js
  src/middlewares/permission/admin.js
  src/middlewares/socket.io.js
  src/models/clan.js
  src/models/planet.js
  src/models/stock-history.js
  src/models/transaction.js
  src/models/user.js
  src/pages/api/admin/eternal.js
  src/pages/api/admin/godmod.js
  src/pages/api/admin/market-manipulator.js
  src/pages/api/admin/user-enforcer.js
  src/pages/api/auth.js
  src/pages/api/clans/[id]/properties.js
  src/pages/api/clans/[id]/stock.js
  src/pages/api/clans/[id]/transfer/fuel.js
  src/pages/api/clans/[id]/transfer/planet.js
  src/pages/api/clans/[id]/transfer/redeem.js
  src/pages/api/clans/[id]/transfer/stock.js
  src/pages/api/planets/[id]/index.js
  src/pages/api/planets/[id]/quest.js
  src/pages/api/planets/[id]/redeem.js
  src/pages/api/planets/index.js
  src/pages/api/stock/index.js
  src/pages/api/users/[id]/index.js
  src/pages/api/users/[id]/money.js
  src/pages/api/users/[id]/transfer/coin.js
  src/pages/index.js
  src/pages/logout.js
  src/utils/axios.js
  yarn.lock
Labels: enhancement

#22 feat: complete backend, donate coin and buy fuel
  package.json
  public/dashboard-bg.png
  src/components/common/Button.js
  src/components/common/Forms/LoginForm.js
  src/components/common/Modal.js
  src/components/common/Navbar/NavMenu.js
  src/components/common/Navbar/Navbar.js
  src/components/common/Navbar/ProfileBar.js
  src/components/contents/Dashboard/AssetsList.js
  src/components/contents/Dashboard/AssetsList/AssetItem.js
  src/components/contents/Dashboard/AssetsList/AssetsList.js
  src/components/contents/Dashboard/Dashboard.js
  src/components/contents/Dashboard/DashboardCotainer.js
  src/components/contents/Dashboard/DonateMoneyModal.js
  src/components/contents/Dashboard/Modals/BuyFuelModal.js
  src/components/contents/Dashboard/Modals/DonateMoneyModal.js
  src/components/contents/Dashboard/TaskList/TaskItem.js
  src/components/contents/Dashboard/TaskList/TaskList.js
  src/components/contents/Map/.gitkeep
  src/components/contents/Stock/.gitkeep
  src/components/contents/dashboard/Balance.js
  src/components/footer/Footer.js
  src/models/battle.js
  src/models/news.js
  src/pages/api/admin/eternal.js
  src/pages/api/admin/godmod.js
  src/pages/api/admin/market-manipulator.js
  src/pages/api/admin/sorayuth.js
  src/pages/api/admin/themis.js
  src/pages/api/clans/[id]/battle/phase01.js
  src/pages/api/clans/[id]/battle/phase02.js
  src/pages/api/clans/[id]/battle/phase03.js
  src/pages/api/clans/[id]/battle/phase04.js
  src/pages/api/clans/[id]/index.js
  src/pages/api/clans/[id]/transactions.js
  src/pages/api/clans/[id]/transfer/fuel.js
  src/pages/api/clans/[id]/transfer/planet.js
  src/pages/api/clans/[id]/transfer/redeem.js
  src/pages/api/clans/[id]/transfer/stock.js
  src/pages/api/news/index.js
  src/pages/index.js
  src/pages/login.js
  src/pages/styles/custom.css
  src/utils/common.js
  yarn.lock
Labels: enhancement

#23 fix: pipeline build error
  src/components/contents/Dashboard/AssetsList.js
  src/components/contents/Dashboard/AssetsList/AssetItem.js
  src/components/contents/Dashboard/DonateMoneyModal.js
  src/components/contents/Dashboard/Modals/BuyFuelModal.js
  src/components/contents/Dashboard/Modals/DonateMoneyModal.js
  src/utils/fetch.js
Labels: bug

#28 Transaction request modal
  src/components/common/Dashboard.js
  src/components/common/Navbar/ClanBar.js
  src/components/common/Navbar/Navbar.js
  src/components/contents/Home/AssetsList/AssetsList.js
  src/components/contents/Home/Home.js
  src/components/contents/Home/Modals/BuyFuelModal.js
  src/components/contents/Home/Modals/DonateMoneyModal.js
  src/components/contents/Home/Modals/TaskVoteModal.js
  src/components/contents/Home/TaskList/TaskItem.js
  src/components/contents/Home/TaskList/TaskList.js
  src/components/contents/Map/Map.js
  src/components/contents/Stock/Stock.js
  src/pages/api/clans/[id]/transfer/fuel.js
  src/pages/api/clans/[id]/transfer/planet.js
  src/pages/api/clans/[id]/transfer/stock.js
  src/pages/map.js
  src/pages/stock.js
Labels: enhancement

#30 feat: stock system and UI big improvement
  public/dashboard-bg-dark.png
  src/components/common/Dashboard.js
  src/components/contents/Home/AssetsList/AssetItem.js
  src/components/contents/Home/AssetsList/AssetsList.js
  src/components/contents/Home/Home.js
  src/components/contents/Home/Modals/BuyFuelModal.js
  src/components/contents/Home/Modals/DonateMoneyModal.js
  src/components/contents/Home/Modals/TaskVoteModal.js
  src/components/contents/Home/NewsList/NewsItem.js
  src/components/contents/Home/NewsList/NewsList.js
  src/components/contents/Home/TaskList/TaskItem.js
  src/components/contents/Home/TaskList/TaskList.js
  src/components/contents/Home/TransactionList/TransactionItem.js
  src/components/contents/Home/TransactionList/TransactionList.js
  src/components/contents/Stock/Stock.js
  src/components/contents/Stock/StockItem.js
  src/components/contents/Stock/StockList.js
  src/components/contents/Stock/TodayPrice.js
  src/pages/api/clans/[id]/transfer/planet.js
  src/pages/api/clans/[id]/transfer/stock.js
  src/pages/api/stock/index.js
  src/pages/stock.js
  src/pages/styles/custom.css
Labels: enhancement

#31 Complete planet map page and improve responsibility
  public/breaking-news.png
  public/general-news.png
  src/components/common/ChangePasswordModal.js
  src/components/common/InputBox.js
  src/components/common/Modal.js
  src/components/common/Modals/SetMoneyModal.js
  src/components/common/Navbar/NavMenu.js
  src/components/common/Navbar/Navbar.js
  src/components/contents/Home/AssetsList/AssetItem.js
  src/components/contents/Home/Home.js
  src/components/contents/Home/Modals/BuyFuelModal.js
  src/components/contents/Home/Modals/DonateMoneyModal.js
  src/components/contents/Home/Modals/TaskVoteModal.js
  src/components/contents/Home/NewsList/NewsItem.js
  src/components/contents/Home/NewsList/NewsList.js
  src/components/contents/Home/NewsList/NewsModal.js
  src/components/contents/Home/TaskList/TaskItem.js
  src/components/contents/Home/TransactionList/TransactionItem.js
  src/components/contents/Home/TransactionList/TransactionList.js
  src/components/contents/Map/Map.js
  src/components/contents/Map/Planet.js
  src/components/contents/Map/PlanetCol.js
  src/components/contents/Map/PlanetConfirmModal.js
  src/components/contents/Map/PlanetModal.js
  src/components/contents/Map/PlanetPopOver.js
  src/pages/api/admin/user-enforcer.js
  src/pages/api/auth.js
  src/pages/api/clans/[id]/battle/phase01.js
  src/pages/api/clans/[id]/transactions.js
  src/pages/styles/custom.css
Labels: enhancement

#32 feat: add transaction logs
  src/components/contents/Home/TransactionList/TransactionItem.js
  src/components/contents/Home/TransactionList/TransactionList.js
  src/components/contents/Map/Planet.js
Labels: enhancement

#35 Fix compile error & improve transaction log and API
  .gitlab-ci.yml
  src/components/contents/Home/TaskList/TaskList.js
  src/components/contents/Home/TransactionList/TransactionItem.js
  src/components/contents/Home/TransactionList/TransactionList.js
  src/components/contents/Map/Map.js
  src/components/contents/Map/PlanetConfirmModal.js
  src/components/contents/Map/PlanetListItem.js
  src/pages/api/admin/sorayuth.js
  src/pages/api/clans/[id]/transfer/stock.js
Labels: enhancement

#36 fix: modal overlapped by navbar
  src/components/common/Modal.js
  src/components/contents/Stock/StockItem.js
Labels: enhancement

#37 Fix time logic in market stock
  src/components/contents/Map/Map.js
  src/components/contents/Stock/Stock.js
  src/pages/api/clans/[id]/transfer/stock.js
  src/pages/api/stock/index.js
Labels: bugfixes

#39 New Stock UI and minor Home UI change
  src/components/common/Dashboard.js
  src/components/common/Navbar/Navbar.js
  src/components/common/Navbar/ProfileBar.js
  src/components/contents/Home/AssetsList/AssetItem.js
  src/components/contents/Home/AssetsList/AssetsList.js
  src/components/contents/Home/Home.js
  src/components/contents/Home/Modals/BuyFuelModal.js
  src/components/contents/Home/Modals/TaskVoteModal.js
  src/components/contents/Home/NewsList/NewsItem.js
  src/components/contents/Home/NewsList/NewsList.js
  src/components/contents/Home/NewsList/NewsModal.js
  src/components/contents/Home/TaskList/TaskItem.js
  src/components/contents/Home/TaskList/TaskList.js
  src/components/contents/Home/TransactionList/TransactionItem.js
  src/components/contents/Home/TransactionList/TransactionList.js
  src/components/contents/Map/Map.js
  src/components/contents/Map/Planet.js
  src/components/contents/Map/PlanetModal.js
  src/components/contents/Stock/Stock.js
  src/components/contents/Stock/StockItem.js
  src/components/contents/Stock/StockList.js
  src/models/battle.js
  src/models/planet.js
  src/models/stock.js
  src/pages/api/admin/market-manipulator.js
  src/pages/api/clans/[id]/transfer/stock.js
  src/pages/api/stock/index.js
  src/pages/styles/custom.css
Labels: UI/UX, enhancement

#41 Improve User interface and User experience on every devices
  README.md
  src/components/contents/Home/AssetsList/AssetItem.js
  src/components/contents/Home/BattleList/BattleItem.js
  src/components/contents/Home/BattleList/BattleList.js
  src/components/contents/Home/Home.js
  src/components/contents/Home/NewsList/NewsItem.js
  src/components/contents/Home/NewsList/NewsList.js
  src/components/contents/Home/NewsList/NewsModal.js
  src/components/contents/Home/TaskList/TaskItem.js
  src/components/contents/Home/TransactionList/TransactionItem.js
  src/components/contents/Home/TransactionList/TransactionList.js
  src/components/contents/Map/Map.js
  src/components/contents/Map/Planet.js
  src/components/contents/Map/PlanetConfirmModal.js
  src/components/contents/Map/PlanetModal.js
  src/components/contents/Map/PlanetPopOver.js
  src/models/clan.js
  src/pages/api/admin/godmod.js
  src/pages/api/clans/[id]/battle/index.js
  src/pages/api/clans/[id]/battle/phase01.js
  src/pages/api/clans/[id]/battle/phase02.js
  src/pages/api/clans/[id]/transfer/planet.js
  src/pages/api/clans/[id]/transfer/redeem.js
  src/pages/map.js
  src/pages/styles/custom.css
Labels: UI/UX, bugfixes

#46 THE PORTAL IS OPEN, WELCOME TO EXPLORATION ERA
  src/components/common/Modal.js
  src/components/contents/Home/BattleList/BattleItem.js
  src/components/contents/Home/BattleList/BattleList.js
  src/components/contents/Home/Home.js
  src/components/contents/Home/Modals/BattleModal.js
  src/components/contents/Home/NewsList/NewsItem.js
  src/components/contents/Home/NewsList/NewsList.js
  src/components/contents/Home/TaskList/TaskItem.js
  src/components/contents/Home/TransactionList/TransactionList.js
  src/components/contents/Map/.gitkeep
  src/components/contents/Map/Map.js
  src/components/contents/Map/MapRule.js
  src/components/contents/Map/Planet.js
  src/components/contents/Map/PlanetConfirmModal.js
  src/components/contents/Map/PlanetListItem.js
  src/components/contents/Map/PlanetModal.js
  src/models/battle.js
  src/pages/api/admin/godmod.js
  src/pages/api/admin/themis.js
  src/pages/api/clans/[id]/battle/index.js
  src/pages/api/clans/[id]/battle/phase01.js
  src/pages/api/clans/[id]/battle/phase02.js
  src/pages/api/clans/[id]/transfer/redeem.js
  src/pages/index.js
  src/pages/map.js
  src/utils/common.js
Labels: enhancement

#47 fix: compile error and reduce depends warn
  src/components/contents/Home/BattleList/BattleList.js
  src/components/contents/Home/Modals/BattleModal.js
  src/components/contents/Home/NewsList/NewsItem.js
  src/components/contents/Map/PlanetModal.js
Labels: bugfixes

#51 refactor: minor missing usability on map and transaction
  src/components/common/Modals/SetMoneyModal.js
  src/components/contents/Home/Modals/BattleModal.js
  src/components/contents/Home/NewsList/NewsModal.js
  src/components/contents/Home/TransactionList/TransactionItem.js
  src/components/contents/Home/TransactionList/TransactionList.js
  src/components/contents/Map/Map.js
  src/components/contents/Map/Planet.js
  src/components/contents/Map/PlanetConfirmModal.js
  src/components/contents/Map/PlanetModal.js
  src/components/contents/Map/PlanetPopOver.js
  src/components/contents/Stock/Stock.js
  src/pages/api/admin/godmod.js
  src/pages/api/admin/user-enforcer.js
  src/pages/api/clans/[id]/battle/phase01.js
  src/pages/api/clans/[id]/battle/phase03.js
  src/pages/api/clans/[id]/transfer/fuel.js
  src/pages/api/clans/[id]/transfer/planet.js
  src/pages/api/clans/[id]/transfer/redeem.js
  src/pages/api/clans/[id]/transfer/stock.js
  src/pages/api/users/[id]/transfer/coin.js
  src/utils/discord.js
Labels: UI/UX, bugfixes, enhancement

#53 feat: balance the travel cost and currency of the universe
  src/components/contents/Map/MapRule.js
  src/pages/api/clans/[id]/battle/phase01.js
  src/pages/api/clans/[id]/battle/phase02.js
Labels: enhancement
